### ISSUE TITLE
Broken with yarn?

### ISSUE THREAD

**Issue by gaearon** [dalemartyn/podcast-player#1]
Not that I care strongly but just noticed I couldn't get it running with yarn. Got some error from React Router.

Maybe you can reproduce this by deleting the package lock and doing another install. Interesting what dependency broke?

**Comment by gaearon** [comment]
I guess maybe these should be pinned instead of `^`.

https://github.com/dalemartyn/podcast-player/blob/b583d3d510167a15450e61d6f42d8e0e50d2996a/package.json#L23-L24

**Comment by dalemartyn** [comment]
Hi Dan, I've pinned them to alpha 5. Hopefully this resolves your issue with yarn. 👍
